### ISSUE TITLE
Feature request: Exclude parts from been validated

### ISSUE THREAD

**Issue by dieppon** [acupofspirt/css-validator-loader#2]
Hi,

I really want a css validator for my project, but i do import libraries, like boostrap and they don't validate.

Would be possible to use some kind of comment wrapper to exclude from been validated?

e.g:

```
/* @exclude */
.font-size{
  font-weight 10px;
}
/* @end */
```

Kind regards

**Comment by acupofspirt** [comment]
@dieppon hi
Sorry, but csstree-validator doesn't have ability to exclude certain styles from validation. You can open an issue or pr to the original repo: [csstree/validator](https://github.com/csstree/validator)
